language: ruby
rvm:
  - 2.1.1

install: bundle install
script: bundle exec jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer