language: ruby
rvm:
  - 2.1.1
cache: bundler

install: bundle install
script: bundle exec jekyll build && htmlproof _site --href-ignore '#' --empty-alt-ignore

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer