# Site settings
title: Goibon's Online Portfolio
email: kasper.lind.sorensen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My name is Kasper Lind Sørensen and I'm a Computer Science student at Aalborg University AAU specialising in computer game programming.
  I have a passion for computer games and when I'm not busy playing them, I like to develop some of my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Goibon
github_username:  Goibon

# Build settings
markdown: kramdown

# Gems
gems: 
 - jekyll-sitemap

# Collections
collections:
  games:
    output: true

permalink: title

exclude: [vendor]

# Compress settings
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: []